[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@thirdweb-dev/=lib/thirdweb-contracts/",
    "forge-std/=lib/forge-std/src/"
]
gas_limit = 30000000
gas_price = 1000000000  # 1 gwei
via_ir = true
optimizer = true
optimizer_runs = 200

# Base Sepolia configuration
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"
mainnet = "https://base-mainnet.infura.io/v3/${INFURA_PROJECT_ID}"
